services:
  api:
    build: .
    image: task-manager:0.2
    ports:
      - "5009:5009"
    environment:
      PORT: 5009
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

# services:
#   api:
#     build: .
#     image: task-manager:0.1
#     ports:
#       - "5009:5009"
#     environment:
#       PORT: 5009
#     restart: unless-stopped